import type { TDHeroConfig, TDHeroId, TDStar } from '../types';
import { getTDStarMultiplier } from './td-game-config';

export const TD_HERO_CONFIG: Record<TDHeroId, TDHeroConfig> = {
  archer: {
    heroId: 'archer',
    name: '弓箭手',
    cost: 4,
    maxHp: 160,
    attackDamage: 24,
    attackInterval: 0.78,
    attackRange: 360,
    armor: 4,
    blockCount: 0,
    guardRadius: 0,
    canAttackAir: true,
    revealStealth: false,
    damageType: 'physical',
    armorPierceRatio: 0.15,
    magicPierceRatio: 0,
    splashRadius: 0,
    tags: ['ranged', 'anti_air'],
    skillIds: ['archer_piercing_arrow', 'archer_multishot'],
  },
  mage: {
    heroId: 'mage',
    name: '法师',
    cost: 5,
    maxHp: 140,
    attackDamage: 34,
    attackInterval: 1.25,
    attackRange: 320,
    armor: 2,
    blockCount: 0,
    guardRadius: 0,
    canAttackAir: false,
    revealStealth: false,
    damageType: 'magic',
    armorPierceRatio: 0,
    magicPierceRatio: 0.2,
    splashRadius: 55,
    tags: ['ranged', 'magic', 'aoe'],
    skillIds: ['mage_frost_ring', 'mage_meteor'],
  },
  warrior: {
    heroId: 'warrior',
    name: '战士',
    cost: 4,
    maxHp: 260,
    attackDamage: 30,
    attackInterval: 1,
    attackRange: 90,
    armor: 12,
    blockCount: 1,
    guardRadius: 95,
    canAttackAir: false,
    revealStealth: false,
    damageType: 'physical',
    armorPierceRatio: 0.08,
    magicPierceRatio: 0,
    splashRadius: 28,
    tags: ['melee', 'blocker'],
    skillIds: ['warrior_cleave', 'warrior_whirlwind'],
  },
  knight: {
    heroId: 'knight',
    name: '骑士',
    cost: 5,
    maxHp: 340,
    attackDamage: 22,
    attackInterval: 1.35,
    attackRange: 85,
    armor: 20,
    blockCount: 2,
    guardRadius: 110,
    canAttackAir: false,
    revealStealth: false,
    damageType: 'physical',
    armorPierceRatio: 0.05,
    magicPierceRatio: 0,
    splashRadius: 0,
    tags: ['melee', 'tank', 'taunt'],
    skillIds: ['knight_taunt', 'knight_holy_shield'],
  },
  assassin: {
    heroId: 'assassin',
    name: '刺客',
    cost: 5,
    maxHp: 180,
    attackDamage: 42,
    attackInterval: 0.95,
    attackRange: 100,
    armor: 6,
    blockCount: 1,
    guardRadius: 105,
    canAttackAir: false,
    revealStealth: true,
    damageType: 'physical',
    armorPierceRatio: 0.25,
    magicPierceRatio: 0,
    splashRadius: 0,
    tags: ['melee', 'burst', 'detect'],
    skillIds: ['assassin_poison_blade', 'assassin_execute'],
  },
  priest: {
    heroId: 'priest',
    name: '牧师',
    cost: 4,
    maxHp: 170,
    attackDamage: 28,
    attackInterval: 1.1,
    attackRange: 300,
    armor: 5,
    blockCount: 0,
    guardRadius: 0,
    canAttackAir: false,
    revealStealth: false,
    damageType: 'healing',
    armorPierceRatio: 0,
    magicPierceRatio: 0,
    splashRadius: 0,
    tags: ['support', 'healer'],
    skillIds: ['priest_chain_heal', 'priest_guardian_field'],
  },
  spearman: {
    heroId: 'spearman',
    name: '枪兵',
    cost: 4,
    maxHp: 220,
    attackDamage: 28,
    attackInterval: 0.9,
    attackRange: 150,
    armor: 10,
    blockCount: 1,
    guardRadius: 105,
    canAttackAir: false,
    revealStealth: false,
    damageType: 'physical',
    armorPierceRatio: 0.3,
    magicPierceRatio: 0,
    splashRadius: 35,
    tags: ['melee', 'pierce'],
    skillIds: ['spearman_line_pierce'],
  },
  alchemist: {
    heroId: 'alchemist',
    name: '炼金师',
    cost: 5,
    maxHp: 150,
    attackDamage: 20,
    attackInterval: 1.15,
    attackRange: 300,
    armor: 3,
    blockCount: 0,
    guardRadius: 0,
    canAttackAir: false,
    revealStealth: false,
    damageType: 'poison',
    armorPierceRatio: 0,
    magicPierceRatio: 0.15,
    splashRadius: 60,
    tags: ['ranged', 'dot', 'aoe'],
    skillIds: ['alchemist_acid_cloud'],
  },
  gunner: {
    heroId: 'gunner',
    name: '炮手',
    cost: 6,
    maxHp: 190,
    attackDamage: 58,
    attackInterval: 1.8,
    attackRange: 380,
    armor: 8,
    blockCount: 0,
    guardRadius: 0,
    canAttackAir: true,
    revealStealth: false,
    damageType: 'explosive',
    armorPierceRatio: 0.15,
    magicPierceRatio: 0,
    splashRadius: 85,
    tags: ['ranged', 'aoe', 'anti_air'],
    skillIds: ['gunner_heavy_barrage'],
  },
  druid: {
    heroId: 'druid',
    name: '德鲁伊',
    cost: 5,
    maxHp: 190,
    attackDamage: 26,
    attackInterval: 1.05,
    attackRange: 330,
    armor: 6,
    blockCount: 1,
    guardRadius: 80,
    canAttackAir: true,
    revealStealth: true,
    damageType: 'magic',
    armorPierceRatio: 0,
    magicPierceRatio: 0.1,
    splashRadius: 35,
    tags: ['ranged', 'control', 'detect'],
    skillIds: ['druid_entangle'],
  },
};

export function getTDHeroConfig(heroId: TDHeroId): TDHeroConfig {
  return TD_HERO_CONFIG[heroId];
}

export function scaleTDHeroStat(value: number, star: TDStar): number {
  return Math.round(value * getTDStarMultiplier(star));
}

export function getScaledTDHeroConfig(heroId: TDHeroId, star: TDStar): TDHeroConfig {
  const base = getTDHeroConfig(heroId);
  return {
    ...base,
    maxHp: scaleTDHeroStat(base.maxHp, star),
    attackDamage: scaleTDHeroStat(base.attackDamage, star),
    attackRange: Math.round(base.attackRange * (1 + (star - 1) * 0.08)),
    armor: Math.round(base.armor * (1 + (star - 1) * 0.35)),
    attackInterval: Math.max(0.35, Number((base.attackInterval * (1 - (star - 1) * 0.07)).toFixed(2))),
    splashRadius: Math.round(base.splashRadius * (1 + (star - 1) * 0.18)),
    blockCount: base.blockCount + (star === 3 && base.blockCount > 0 ? 1 : 0),
    revealStealth: base.revealStealth || heroId === 'assassin' || heroId === 'druid',
    canAttackAir: base.canAttackAir || (star >= 3 && heroId === 'mage'),
  };
}

export const TD_MVP_HERO_IDS: TDHeroId[] = ['archer', 'mage', 'warrior', 'knight', 'assassin', 'priest'];
export const TD_ALL_HERO_IDS: TDHeroId[] = ['archer', 'mage', 'warrior', 'knight', 'assassin', 'priest', 'spearman', 'alchemist', 'gunner', 'druid'];
