import { EnemyConfig, EnemyId } from '../models/types';

export const ENEMY_CONFIG: Record<EnemyId, EnemyConfig> = {
  slime: {
    id: 'slime',
    name: '史莱姆',
    maxHp: 80,
    moveSpeed: 120,
    goldReward: 1,
    attackDamage: 8,
    attackInterval: 1.2,
    detectionRange: 120,
    attackRange: 56,
    separationWeight: 0.8,
  },
  wolf: {
    id: 'wolf',
    name: '恶狼',
    maxHp: 140,
    moveSpeed: 165,
    goldReward: 2,
    attackDamage: 14,
    attackInterval: 1,
    detectionRange: 150,
    attackRange: 58,
    separationWeight: 1,
  },
  brute: {
    id: 'brute',
    name: '重甲怪',
    maxHp: 320,
    moveSpeed: 85,
    goldReward: 4,
    attackDamage: 22,
    attackInterval: 1.4,
    detectionRange: 135,
    attackRange: 62,
    separationWeight: 0.5,
  },
};
